### ISSUE TITLE
Wrong PropertyGroups in readme

### ISSUE THREAD

**Issue by KryziK** [BepInEx/BepInEx.Templates#3]
The README.md specifies that AssemblyName, Description, and Version will generate the PLUGIN_GUID, PLUGIN_NAME, and PLUGIN_VERSION respectively. Quoted below:

Define the following properties in your `csproj`:

```xml
<AssemblyName>Example.Plugin</AssemblyName>
<Description>My first plugin</Description>
<Version>1.0.0</Version>
```

this will generate the following class:

```cs
using System;

internal static class MyPluginInfo
{
    public const string PLUGIN_GUID = "Example.Plugin";
    public const string PLUGIN_NAME = "My first plugin";
    public const string PLUGIN_VERSION = "1.0.0";
}
```

However, the props file is actually using AssemblyName, Product, and Version.

```xml
<BepInExPluginGuid Condition="'$(BepInExPluginGuid)' == ''">$(AssemblyName)</BepInExPluginGuid>
<BepInExPluginName Condition="'$(BepInExPluginName)' == ''">$(Product)</BepInExPluginName>
<BepInExPluginVersion Condition="'$(BepInExPluginVersion)' == ''">$(Version)</BepInExPluginVersion>
```

This would not be immediately obvious to somebody that is using the plugin but not cloning/using the props file manually, as they'd have to dig into the nuget reference to see the difference.

Edit: @ghorsington  I don't mind submitting a PR, but wasn't sure which one you'd like to be the correct one, the docs or the props?

**Comment by kkaja123** [comment]
I have to imagine that the readme should be updated, as to avoid breaking existing usage of this. Additionally, it probably makes more sense to use the "Product" property, since it represents a name more than the "Description" property should.

Product attribute: https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assemblyproductattribute.product?view=net-7.0#system-reflection-assemblyproductattribute-product
